### ISSUE TITLE
Package install ASCII error from long_description=open('README')?

### ISSUE THREAD

**Issue by moscow25** [salesforce/pytorch-qrnn#8]
When pulling the repo in my Docker container, I'm able to run only if I remove the `long_description=open('README.md').read()` line from the `setup.py` script.
https://github.com/salesforce/pytorch-qrnn/blob/master/setup.py#L8

Not sure what I could do in the Docker to fix this, without making a fork and removing that line. Running in Python 3.5.

Have you gotten this error? I guess Python/ASCII reading problems will always be with us. Would love to find a workaround and not have to fork. Thanks! 

```
Step 3/3 : RUN pip install cupy pynvrtc git+https://github.com/Smerity/pytorch-qrnn
 ---> Running in 25baaa71b04c
Collecting git+https://github.com/Smerity/pytorch-qrnn
  Cloning https://github.com/Smerity/pytorch-qrnn to /tmp/pip-a0ij_ogt-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-a0ij_ogt-build/setup.py", line 8, in <module>
        long_description=open('README.md').read(),
      File "/opt/conda/envs/pytorch-py35/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5411: ordinal not in range(128)
```

**Comment by Smerity** [comment]
Blargh. Tempted to kill the `long_description` line until I can fix this. Seems an extreme pain. Sorry for that :S

**Comment by Smerity** [comment]
Fixed this by removing the `long_description` line but I'll leave this open until I have a better fix. Thanks for bringing it up @moscow25!

**Comment by moscow25** [comment]
We can put a man on the moon, but not if there's ASCII and Py2/Py3 compatibility issues involved. Thanks!
