### ISSUE TITLE
Error in executing QRNN

### ISSUE THREAD

**Issue by michjk** [salesforce/pytorch-qrnn#9]
Hello,
I got error when I run my modified code from example.
```
import time

import numpy as np

import torch
import torch.nn as nn

import torchqrnn.forget_mult
from torchqrnn import QRNN

class Model(nn.Module):

    def __init__(self, hidden_size=1024, layers=3, vocab=100):
        super(Model, self).__init__()

        self.embedding = nn.Embedding(vocab, hidden_size)

        self.rnn = QRNN(hidden_size, hidden_size, num_layers=layers)

    def forward(self, x):
        x = self.embedding(x)
        out, hidden = self.rnn(x)
        return out[:-1]

H = 256
SEQ = 100
BATCH = 64

H = 1024
SEQ = 500
BATCH = 128

LOOPS = 500

np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed(42)

x = torch.autograd.Variable(torch.LongTensor(np.random.randint(0, 100, [BATCH, SEQ])))
x = x.cuda()

np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed(42)

model = Model(H)
model = model.cuda()
model(x)
```
The error message is:
```
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    model(x)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 22, in forward
    out, hidden = self.rnn(x)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torchqrnn/qrnn.py", line 160, in forward
    input, hn = layer(input, None if hidden is None else hidden[i])
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torchqrnn/qrnn.py", line 95, in forward
    C = ForgetMult()(F, Z, hidden, use_cuda=self.use_cuda)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torchqrnn/forget_mult.py", line 175, in forward
    if hidden_init is None: return GPUForgetMult()(f, x) if use_cuda else CPUForgetMult()(f, x)
  File "/home/michael/.virtualenvs/fyp-pytorch/local/lib/python2.7/site-packages/torchqrnn/forget_mult.py", line 127, in forward
    self.forget_mult(grid=grid, block=(grid_hidden_size, 1), args=[result.data_ptr(), f.data_ptr(), x.data_ptr(), seq_size, batch_size, hidden_size], stream=self.stream)
  File "cupy/cuda/function.pyx", line 143, in cupy.cuda.function.Function.__call__
TypeError: 'float' object cannot be interpreted as an index
```
I am using CUDA 8.0 and python 2.7. Thanks.

**Comment by Smerity** [comment]
This code has not been tested on Python 2.7 so I am uncertain where the issue may lie. I'd be happy to include backward compatible changes if you can find them.

Before you modified the code, could you run the example successfully..? Your code above works for me regardless.

**Comment by michjk** [comment]
I tried to run the example previously. However it produce error:
```
Traceback (most recent call last):
  File "multigpu_dataparallel.py", line 48, in <module>
    model = Model(H, parallel=False)
  File "multigpu_dataparallel.py", line 11, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```
I realized there is problem in calling super constructor. Then I change it into 
```
super(Model, self).__init__()
```
Which is suggested from pytorch tutorial.
And then I run it again and get the same error. I suspect the error in cupy. Thanks.

**Comment by Smerity** [comment]
These issues all seem related to Python 2 versus Python 3 actually. The
super issue explicitly has this and I would guess that the float issue is
that Python's default division is integer compared to Python 3 which is
float.

While we will happily accept pull requests adding Python 2 support we don't
have an explicit goal of supporting it at this time sorry.
